name: EKS Deploy

on:
  workflow_call:
    inputs:
      tf_version:
        description: 'Default=latest.'
        required: false
        type: string
        default: latest
      gh_environment:
        description: 'Specifies the GitHub deployment environment.'
        required: false
        type: string
        default: null

jobs:
  deploy_eks:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install kubectl
        run: |
            sudo apt-get update && sudo apt-get install -y kubectl
            kubectl version --client
      
      - name: Configure AWS Credentials
        run: |
              echo "[default]" > ~/.aws/credentials
              echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
              echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
              aws eks --region us-east-1 update-kubeconfig --name demo

      - name: Deploy to EKS
        run: |
            kubectl apply -f deployment.yaml
            kubectl apply -f public-lb.yaml
            kubectl apply -f cluster-autoscaler.yaml
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Check Pods
        run: |
            kubectl get pods --all-namespaces
