name: EKS Deploy

on:
  workflow_call:
    inputs:
      tf_version:
        description: 'Default=latest.'
        required: false
        type: string
        default: latest
      gh_environment:
        description: 'Specifies the GitHub deployment environment.'
        required: false
        type: string
        default: null

env:
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
jobs:
  deploy_eks:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install kubectl
        run: |
          sudo apt-get update && sudo apt-get install -y kubectl
          kubectl version --client
          aws eks --region us-east-1 update-kubeconfig --name demo
          kubectl apply -f deployment.yaml
          kubectl apply -f public-lb.yaml
          kubectl apply -f cluster-autoscaler.yaml

      - name: Check Pods
        run: |
          kubectl get pods --all-namespaces
