name: EKS Deploy

on:
  workflow_call:
    inputs:
      tf_version:
        description: 'Default=latest.'
        required: false
        type: string
        default: latest
      gh_environment:
        description: 'Specifies the GitHub deployment environment.'
        required: false
        type: string
        default: null

jobs:
  deploy_eks:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install kubectl
        run: |
            sudo apt-get update && sudo apt-get install -y kubectl
            kubectl version --client
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr  
        uses: aws-actions/amazon-ecr-login@v1

      - name: Deploy to EKS
        run: |
            kubectl apply -f deployment.yaml
            kubectl apply -f public-lb.yaml
            kubectl apply -f cluster-autoscaler.yaml
        # env:
        #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Check Pods
        run: |
            kubectl get pods --all-namespaces
