
name: Deploy

on:
  push:
    branches:
      - feature2

env:
    TF_CLOUD_ORGANIZATION: "Devsecops-org"
    TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
    TF_WORKSPACE: "terraform-github-actions"
    CONFIG_DIRECTORY: "./"
      

jobs:
  Terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Terraform Setup
      uses: hashicorp/setup-terraform@v1


    - name: Terraform Init
      run: |
        cd Terraform
        terraform init -backend-config="token=${TF_API_TOKEN}"

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Upload Configuration
      uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
      id: plan-upload
      with:
        workspace: ${{ env.TF_WORKSPACE }}
        directory: ${{ env.CONFIG_DIRECTORY }}
        speculative: true
      
