name: Terraform Apply

on:
  workflow_dispatch:

env:
  TF_CLOUD_ORGANIZATION: "Devsecops-org"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "terraform-github-actions"
  CONFIG_DIRECTORY: "./"

jobs:
  terraform_apply:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Upload Configuration
      uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
      id: plan-upload
      with:
        workspace: ${{ env.TF_WORKSPACE }}
        directory: ${{ env.CONFIG_DIRECTORY }}
        speculative: true

    - name: Configure AWS Credentials
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
        # aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        # aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        
    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: |
        terraform apply -auto-approve

    - name: Kubectl Apply
      if: success()  
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f public-lb.yaml
        kubectl apply -f cluster-autoscaler.yaml
        
  
    - name: Kubectl Get Pods
      if: success()  
      run: |
        kubectl get pods --all-namespaces

    - name: Capture Outputs
      id: terraform-outputs
      run: |
        echo "::set-output name=terraform_apply_output::$(terraform output -json)"
